name: Packaging

on:
  pull_request:
  merge_group:

jobs:
  packaging:
    uses: tskit-dev/.github/.github/workflows/python-packaging.yml@v14
    with:
      # The sc2ts cli is only available with the sc2ts[inference] install
      # cli-test-cmd: sc2ts --help
